//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyntecCNC_Hanhai {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class CNCIP : global::System.Configuration.ApplicationSettingsBase {
        
        private static CNCIP defaultInstance = ((CNCIP)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CNCIP())));
        
        public static CNCIP Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.31.104")]
        public string 一号机 {
            get {
                return ((string)(this["一号机"]));
            }
            set {
                this["一号机"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.31.103")]
        public string 二号机 {
            get {
                return ((string)(this["二号机"]));
            }
            set {
                this["二号机"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.31.123")]
        public string 三号机 {
            get {
                return ((string)(this["三号机"]));
            }
            set {
                this["三号机"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 四号机 {
            get {
                return ((string)(this["四号机"]));
            }
            set {
                this["四号机"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.31.102")]
        public string 五号机 {
            get {
                return ((string)(this["五号机"]));
            }
            set {
                this["五号机"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.31.101")]
        public string 六号机 {
            get {
                return ((string)(this["六号机"]));
            }
            set {
                this["六号机"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 七号机 {
            get {
                return ((string)(this["七号机"]));
            }
            set {
                this["七号机"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 八号机 {
            get {
                return ((string)(this["八号机"]));
            }
            set {
                this["八号机"] = value;
            }
        }
    }
}
